import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { assessSnapshot } from "./drift.js";
import { loadDvnMeta, resolveDvn } from "./lz-config.js";
import { getSnapshot, latestVerdict } from "./snapshot-store.js";
import { getChainRef, chainDisplayName, sentinelChain } from "./chain-registry.js";
import type { WatchedOft } from "../types.js";

const DEEPSEEK_KEY = process.env.DEEPSEEK_API_KEY;

const REFERENCE = (() => {
  try {
    const dir = dirname(fileURLToPath(import.meta.url));
    return readFileSync(join(dir, "oft-security-reference.md"), "utf8");
  } catch {
    return "";
  }
})();

// ── LLM full report writer ────────────────────────────────────────────────────

const REPORT_SYSTEM = (REFERENCE
  ? `${REFERENCE}\n\n---\n`
  : "") +
`You are the OFT Sentinel report engine. You will be given structured on-chain security facts for a LayerZero OFT. Write a complete markdown security report.

Rules:
- Use ONLY the facts provided. Never invent DVN names, addresses, counts, or scores.
- Output plain markdown. Do not wrap in a code block.
- Start with: # OFT Sentinel — {ticker} Security Report
- Then a metadata line: **{address}** · {chain} · generated {generated} · Score {score}/100 · {riskLevel}
  Use the {chain} value from the facts verbatim. Never name a chain the facts do not state.
- Then these sections in order:

## Summary
2-4 sentences. State the overall risk level, what the main findings are, and the protocol's cross-chain footprint (number of active corridors). Be direct.

## Findings
First, a markdown table with columns: | Severity | Check | Detail |
Then, for each CRITICAL or HIGH finding, write a short paragraph (2-3 sentences) explaining what it means specifically for this OFT and why it matters. Skip MEDIUM/LOW/PASS findings in prose — the table covers them.

## DVN Configuration
First, a markdown table with columns: | Corridor | Required DVNs | Confirmations | Send library |
Then, a paragraph interpreting what this configuration means in practice: how many independent verifiers are protecting each corridor, whether the DVN set is diverse, and whether the library setup introduces any upgrade risk.

## Attack Scenario
Write a concrete, specific scenario: given the actual findings and DVN config above, describe the realistic attack path an adversary would take if they exploited the most critical weakness. Name the specific DVN or library involved. Be concise (3-5 sentences). If the configuration is healthy (score ≥ 85), explain why the most obvious attack vectors are closed.

## Trust Assumptions
3-5 bullet points. Each must name a specific DVN or contract from the facts. Do not write generic statements.

## Recommendations
2-5 bullet points, ordered by priority (highest impact first). Each must be a concrete action the protocol team can take, referencing the specific finding it addresses.

## On-chain Record
One line. If an attestation is provided, give its tx hash and link. If it is null,
state plainly that no attestation has been written for this configuration — do NOT
say or imply why, and in particular do not claim that nothing has drifted: an
attestation can be absent because the config never changed, because the attest
scope excluded this asset, or because the write failed, and the facts here cannot
distinguish those.

---
*Generated by OFT Sentinel — deterministic on-chain reads, AI-written report. Not financial advice.*`;

/** Call DeepSeek to write the full report markdown. Returns null on any failure. */
async function writeReport(facts: unknown): Promise<string | null> {
  if (!DEEPSEEK_KEY) return null;
  try {
    const res = await fetch("https://api.deepseek.com/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${DEEPSEEK_KEY}` },
      body: JSON.stringify({
        model: "deepseek-chat",
        temperature: 0.2,
        messages: [
          { role: "system", content: REPORT_SYSTEM },
          {
            role: "user",
            content: "Facts:\n```json\n" + JSON.stringify(facts, null, 2) + "\n```\n\nWrite the full report now.",
          },
        ],
      }),
    });
    if (!res.ok) return null;
    const j = (await res.json()) as any;
    return (j.choices?.[0]?.message?.content as string | undefined) ?? null;
  } catch {
    return null;
  }
}

// Keyed by address only — one entry per OFT. The capturedAt comparison ensures we
// regenerate when a new snapshot arrives without letting old entries accumulate.
const cache = new Map<string, { capturedAt: number; markdown: string }>();

/** Generate (or return cached) a full AI-written markdown audit report for one watched OFT. */
export async function generateReport(w: WatchedOft): Promise<string | null> {
  const snap = getSnapshot(w.address, w.chainId);
  if (!snap) return null; // not polled yet

  const cacheKey = w.address.toLowerCase();
  const hit = cache.get(cacheKey);
  if (hit && hit.capturedAt === snap.capturedAt) return hit.markdown;

  const dvnMeta = await loadDvnMeta();
  // A DVN's identity is the (chainKey, address) PAIR, and send-side DVNs live on
  // the OFT's own chain. Resolving against a hardcoded "mantle" is the bug
  // rules 2.1.0 fixed in drift.ts and routes/sentinel.ts:90 fixed for /status —
  // it survived here. It is not cosmetic: lz-config.ts:553 records that
  // 0x28b6140e… is a DEAD placeholder on flare and "LayerZero Labs" on mantle,
  // so a Flare OFT's report could NAME A DVN THAT IS NOT THERE. Unknown chain →
  // null → resolveDvn returns an address fragment, never a borrowed name.
  const srcChainKey = getChainRef(w.chainId)?.chainKey ?? null;
  const { findings, score, riskLevel } = await assessSnapshot(snap, w.ticker);
  const verdict = latestVerdict(w.address, w.chainId);
  const generated = new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC";

  const facts = {
    ticker: w.ticker,
    address: w.address,
    // The chain the OFT actually lives on, not a literal. Every report said
    // "Mantle"; on this instance every asset is on Flare.
    chain: chainDisplayName(srcChainKey),
    generated,
    score,
    riskLevel,
    owner: snap.owner ?? null,
    ownerIsContract: snap.ownerIsContract,
    proxyAdmin: snap.proxyAdmin ?? null,
    proxyAdminIsMultisig: snap.proxyAdminIsMultisig,
    findings: findings.map((f) => ({ severity: f.severity, check: f.check, detail: f.detail })),
    corridors: snap.routes
      .filter((r) => r.isActive && r.uln)
      .map((r) => ({
        corridor: r.chainName,
        requiredDVNCount: r.uln!.requiredDVNCount,
        requiredDVNs: r.uln!.requiredDVNs.map((a) => resolveDvn(a, srcChainKey, dvnMeta)),
        optionalDVNs: r.uln!.optionalDVNs.map((a) => resolveDvn(a, srcChainKey, dvnMeta)),
        optionalThreshold: r.uln!.optionalDVNThreshold,
        confirmations: r.uln!.confirmations,
        // `sendLibIsDefault` is boolean | null, and null means the library was
        // not readable this cycle. `!null` is `true`, so the plain negation
        // asserted "pinned" — the reassuring answer — for exactly the case
        // where nothing was read. Unknown stays unknown.
        sendLibPinned: r.sendLibIsDefault === null || r.sendLibIsDefault === undefined
          ? null
          : !r.sendLibIsDefault,
      })),
    // Link resolves to the chain our registry is on, from the same env the
    // attestor signs against. url is null when that chain has no known explorer —
    // the hash is still stated, so the fact survives without a broken link.
    attestation: verdict?.attestTxHash
      ? {
          txHash: verdict.attestTxHash,
          url: sentinelChain().explorer ? `${sentinelChain().explorer}/tx/${verdict.attestTxHash}` : null,
        }
      : null,
  };

  const md = await writeReport(facts);
  if (!md) return null;

  // Deterministic coverage disclaimer — appended outside the LLM so it is always
  // present and accurate. Sentinel reads EVM corridors only; an OFT may also bridge
  // to non-EVM chains (e.g. Solana, Aptos, TON) whose send-side config is readable
  // on the source chain's endpoint but whose receive-side verification needs
  // non-EVM tooling. (The disclaimer text itself names no chain, and must not.)
  const coverage = `\n\n---\n\n*Coverage: Sentinel monitors **EVM corridors**. Non-EVM destinations ` +
    `(Solana, Aptos, TON, Sui, etc.) are not yet monitored — this report does not cover them. ` +
    `Full non-EVM corridor verification is on the LSIN roadmap.*\n`;
  const withCoverage = md + coverage;

  cache.set(cacheKey, { capturedAt: snap.capturedAt, markdown: withCoverage });
  return withCoverage;
}
